[network]
name = "testnet"
stacks_node_rpc_address = "https://api.testnet.hiro.so"
deployment_fee_rate = 10

[accounts.deployer]
mnemonic = "relax text eager hurry follow east local soldier carry hen comic earn brown few clay absorb apple miss garlic lunch banner reject force alter"
